name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - Makefile
      - README.md
      - .gitignore
  workflow_dispatch: {}

jobs:
  push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.92.2"

      - name: Generate Static Content
        run: make Generate

      - name: Commit to GitHub Pages (Feggah.github.io)
        run: |
          cd public
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Deploy generated content"

      - name: Push to GitHub Pages (Feggah.github.io)
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          repository: Feggah/Feggah.github.io
