name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - Makefile
      - README.md
      - .gitignore
  workflow_dispatch: {}

jobs:
  push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.92.2"

      - name: Generate Static Content
        run: make generate

      - name: Push to GitHub Pages (Feggah.github.io)
        working-directory: ./public
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.email "gabriel@feggah.com"
          git config --global user.name "Feggah"
          git add .
          git log
          git commit -m "Deploy generated content"
          git push

      - name: Update submodule reference
        run: |
          git add .
          git commit -s -m "Update submodule"
          git push
